

services:
  postgres:
    container_name: postgres
    image: postgres:13  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
   
