

services:
  postgres:
    container_name: postgres
    image: postgres:13  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - my-networks
    
  airflow:
    container_name: airflow
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.9.0
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/hospital_db
    ports:
        - "8080:8080"
    volumes:
      - ./airflow_dag/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts

    depends_on:
      - postgres
    command: >
      bash -c "airflow db migrate && airflow standalone"
    networks:
      - my-networks
networks:
  my-networks:
    driver: bridge
   
